### ISSUE TITLE
Управление мотором (BMSD) с использованием программы

### ISSUE THREAD

**Issue by AsriFox** [DRONE520/DRONE520-main#10]
Сайт: https://electroprivod.ru/bdc-driver_bmsd.htm
Данные авторизации:
user3 : ad9OnIr9
Контакты технической службы:
Инженер обособленного подразделения  ООО"НПО ЭЛЕКТРОПРИВОД"
Колодко Денис Андреевич
Тел.: +7(499)-938-93-91 доб. 109
denis.kolodko@electroprivod.ru

**Comment by sergmin** [comment]
Статус задачи?

**Comment by AsriFox** [comment]
В репозитории KABESTANE находится рабочая версия консольного приложения. С его помощью можно осуществлять управление мотором, исполняя все доступные команды и получая необходимый отклик от контроллера.
Значимой особенностью является поведение команды запроса статуса. Оно описано в файле README.md репозитория KABESTANE.
Код программы готов к интегрированию в QGroundControl в качестве фреймворка интерфейса мотора. Алгоритм, осуществляющий автоматический подсчёт требуемого количества оборотов для достижения заданной длины кабеля, будет разработан в дальнейшем.
