### ISSUE TITLE
Познакомиться с материалами Миколайчука по NanoPi

### ISSUE THREAD

**Issue by sergmin** [DRONE520/DRONE520-main#12]
Познакомиться с [материалами Миколайчука по NanoPi](https://github.com/DRONE520/DRONE520-main/wiki/%D0%A1%D0%9F%D0%9E-%D0%B1%D0%BE%D1%80%D1%82%D0%BE%D0%B2%D0%BE%D0%B9-%D0%B2%D1%8B%D1%87%D0%B8%D1%81%D0%BB%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B9-%D0%BF%D0%BB%D0%B0%D1%82%D1%84%D0%BE%D1%80%D0%BC%D1%8B)

**Comment by petrolingus** [comment]
Добрый день, с материалами ознакомились.
