### ISSUE TITLE
ПО для проксирования MAVLink на C++

### ISSUE THREAD

**Issue by sergmin** [DRONE520/DRONE520-main#13]
ПО для проксирования MAVLink на C++;
https://microsoft.github.io/AirSim/mavlinkcom/

**Comment by petrolingus** [comment]
Добрый день, основная задача по созданию прокси сервера для микрокомрьютера NanoPI была выполенна. На данный момент [исходный код проекта](https://github.com/petrolingus/DroneMavLinkTransport) расположен в моем личном репозитории, однако, стоит создать репозиторий внутри этой организации.
