### ISSUE TITLE
Оформить отчет по теме "СПО бортовой вычислительной платформы"

### ISSUE THREAD

**Issue by sergmin** [DRONE520/DRONE520-main#3]
Оформить отчет по теме "СПО бортовой вычислительной платформы":

1. Цель
2. Краткое описание встраиваемой ОС
3. Развертывание встраиваемой ОС для микроконтроллеров АРМ
4. Кросс-разработка программ для встраиваемой ОС для микроконтроллеров АРМ
5. Развертывание программ на встраиваемой ОС для микроконтроллеров АРМ
6. Заключение

**Comment by sergmin** [comment]
Отчет оформить на страничке xWiki: https://github.com/DRONE520/DRONE520-main/wiki/%D0%A1%D0%9F%D0%9E-%D0%B1%D0%BE%D1%80%D1%82%D0%BE%D0%B2%D0%BE%D0%B9-%D0%B2%D1%8B%D1%87%D0%B8%D1%81%D0%BB%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B9-%D0%BF%D0%BB%D0%B0%D1%82%D1%84%D0%BE%D1%80%D0%BC%D1%8B

**Comment by sergmin** [comment]
Статус задачи?

**Comment by nmikolaychuk** [comment]
Отчет оформлен.

**Comment by sergmin** [comment]
В течение недели (до 15.11.2021) необходимо освоить технологию удаленной отладки программ на nanoPi. Соотв. информацию внести в отчет

**Comment by nmikolaychuk** [comment]
Открыта задача по освоению технологии удаленной отладки на NanoPi.

**Comment by nmikolaychuk** [comment]
Статус задачи: в процессе освоения.
Была произведена попытка реализации удаленного отладчика с использованием IDE Eclipse, gdbserver и toolchain компилятора arm-cortexa9-linux-gnueabihf.
На текущий момент использование технологии приводит к ошибкам. В дальнейшем планируется устранение полученных ошибок и занесение соответствующей информации в отчет.

**Comment by nmikolaychuk** [comment]
Технология удаленной отладки программ на NanoPi успешно освоена.

**Comment by sergmin** [comment]
Отлично! Теперь нужно добиться интеграции разрабатываемой программы с внешними зависимостями. Например, с библиотекой OpenCV. В отчет включить соответствующий раздел.

**Comment by nmikolaychuk** [comment]
Открыта задача по интеграции разрабатываемой программы с внешними зависимостями, в частности с библиотекой OpenCV.

**Comment by nmikolaychuk** [comment]
Была проведена интеграция разрабатываемой программы с библиотекой OpenCV.

**Comment by nmikolaychuk** [comment]
Текущий прогресс добавлен в отчет на Wiki.

**Comment by nmikolaychuk** [comment]
Была начата разработка системы контурного анализа изображения на предмет наличия соответствующей [метки](https://github.com/DRONE520/OCP/blob/master/docs/label.jpg). На данный момент осуществляется анализ вложенности контуров. Иерархия найденных контуров сопоставляется с ожидаемой меткой. Это позволяет распознавать вышеуказанную метку на изображении. Исходный код программы указан в [репозитории](https://github.com/DRONE520/OCP/blob/master/src/video_capture.cpp) проекта. В дальнейшем планируется добавить дополнительный анализ формы вложенных контуров.

**Comment by sergmin** [comment]
13.05.2022 в 9:10 в 517 состоится защита результатов практики. Необходимо подготовить печатную версию отчета, доклад (с презентацией). Печатную версию отчета представить мне 12.05.2022 до 16:00. На титульном листе расписаться.

**Comment by nmikolaychuk** [comment]
Исправлены замечания в отчете.
