### ISSUE TITLE
Оформить отчет по теме "Подключение периферии к контроллеру Pixhawk"

### ISSUE THREAD

**Issue by sergmin** [DRONE520/DRONE520-main#4]
Оформить отчет по теме "Подключение периферии к контроллеру Pixhawk":

1. Цель
2. Описание возможностей контроллера Pixhawk в части подключения периферийного оборудования (датчиков, исполнительных устройств)
3. Способы подключения периферийного оборудования:
  - сервоприводов;
  - акустического датчика;
  - реле для включения и выключения бортового оборудования.
4. Заключение

**Comment by sergmin** [comment]
Отчет оформить на страничке Wiki: https://github.com/DRONE520/DRONE520-main/wiki/%D0%9F%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D0%B5%D1%80%D0%B8%D1%84%D0%B5%D1%80%D0%B8%D0%B8-%D0%BA-%D0%BA%D0%BE%D0%BD%D1%82%D1%80%D0%BE%D0%BB%D0%BB%D0%B5%D1%80%D1%83-Pixhawk

**Comment by sergmin** [comment]
https://github.com/albina666 отсутствует в списке участников проекта

**Comment by sergmin** [comment]
Отчет не оформлен

**Comment by sergmin** [comment]
Задача не выполнена в указанный срок,  AlinaChugrina и albina666 отсутствовали на занятиях 08.11.2021

**Comment by sergmin** [comment]
Отчет по прежнему пустой - задание не выполняется вторую неделю подряд.

**Comment by sergmin** [comment]
Констатирую, что работа над проектом не ведется третью неделю.

**Comment by NatashaPinegina** [comment]
В руководстве PX4 указано несколько поддерживаемых дальномеров, использующих инфракрасную технологию (TeraRanger Rangefinders, PSK-CM8JL65-CC5). Какой будет использоваться в проекте?

**Comment by NatashaPinegina** [comment]
Модуль реле, 2-канала, FLASH-I2C : https://iarduino.ru/shop/Expansion-payments/rele-2ch-i2c.html

**Comment by sergmin** [comment]
Для параметров дальномера Maxbotics нужно уточнить:
- сохраняются ли значения параметров после выключения и послед. включения питания Pixhawk;
- определения параметров EKF2_RNG_SFE, EKF2_RNG_NOISE (сейчас непонятно их назначение);
- какими принципами нужно руководствоваться, выбирая значения таких параметров как: EKF2_RNG_DELAY, EKF2_RNG_SFE, EKF2_RNG_NOISE.

**Comment by sergmin** [comment]
1. В документе так и остался "автомобиль".
2. Пример взаимодействия с устройствами на шине I2C описывает программу на Arduino, а надо для Pixhawk

**Comment by NatashaPinegina** [comment]
Замечания исправлены.

**Comment by NatashaPinegina** [comment]
Замечания по отчету в Wiki исправлены.
