### ISSUE TITLE
Оформить отчет по теме "СПО симуляции БПЛА"

### ISSUE THREAD

**Issue by sergmin** [DRONE520/DRONE520-main#6]
Оформить отчет по теме "СПО симуляции БПЛА":

1. Цель
2. Архитектура ПО симуляции БПЛА
3. Способы симуляции окружения для спо БПЛА
3. Сборка ПО симуляции БПЛА
4. Сборка СПО контроллера Pixhawk для отладки в симуляционном окружении
5. Способы расширения функциональности СПО симуляции БПЛА (добавление внешних факторов в симуляцию мира)
6. Заключение

**Comment by NatashaPinegina** [comment]
Отчет оформлен

**Comment by sergmin** [comment]
Предлагаю добавить в симуляцию такой внешний фактор, как нить, заданной длины. Нужно описать как это сделать и провести эксперимент (в симуляции) - описать результаты эксперимента.

**Comment by NatashaPinegina** [comment]
Расширена теоретическая часть, касающаяся пункта 6 (Способы расширения функциональности СПО симуляции БПЛА (добавление внешних факторов в симуляцию мира)): рассмотрена возможность добавление "мира", имитация обзорной камеры, а так же добавление/создание моделей в Gazebo.

**Comment by NatashaPinegina** [comment]
Переустановили Ubuntu, установили необходимые зависимости, заново установили и собрали gazebo под px4.

**Comment by sergmin** [comment]
"заново установили и собрали gazebo" - симуляция работает?

**Comment by NatashaPinegina** [comment]
Да, симуляция работает. На данном этапе возникли проблемы с установкой PX4-SITL-gazebo.

**Comment by NatashaPinegina** [comment]
Так как в самом Gazebo, а так же в рассмотренном нами репозитории PX4-SITL_gazebo, нет модели нити (веревки), было принято решение, строить объект с нуля. Для этого во встроенном редакторе использовались геометрические примитивы - sphere, между которыми были добавлены связи. На данном этапе модель не обладает достаточными физическими свойствами. Алгоритм создания модели (добавление примитивов и связи между ними) описан в Wiki: пункт "Алгоритм создания моделей".

**Comment by NatashaPinegina** [comment]
Добавила связи между шарами (тип ball).
Процесс добавления модели в gazebo и взаимодействие с ней в режиме симуляции:
https://www.youtube.com/watch?v=I3KfXrbiie0

**Comment by NatashaPinegina** [comment]
Написан скрипт сборки. К модели "веревки" с одной стороны добавлен тяжелый блок для прикрепления ее к земле, связь между веревкой и блоком,такая же как между шарами (ball). Далее планируется добавить аналогичную связь между вторым концом веревки и квадрокоптером. Исходный код в репозитории (https://github.com/DRONE520/CS).

**Comment by sergmin** [comment]
13.05.2022 в 9:10 в 517 состоится защита результатов практики. Необходимо подготовить печатную версию отчета (два раздела: симуляция и периферия), доклад (с презентацией). Печатную версию отчета представить мне 12.05.2022 до 16:00. На титульном листе расписаться.

**Comment by NatashaPinegina** [comment]
Отчет, написанный к 13.05, включает в себя одновременно 2 части: подключение периферии и спо симуляции. Отчет доступен по ссылке https://drive.google.com/drive/folders/1Iv9BFmlafSOw54mHfENH4ixD55lihZlS?usp=sharing
Удалось присоединить модель веревки к квадрокоптеру (скрин модели и видео работы программы на данный момент также доступны по прикрепленной ссылке). Однако при попытке поднять квадрокоптер в воздух, модель пока ведет себя неадекватно. В дальнейшем планируется это исправить.

**Comment by NatashaPinegina** [comment]
При запуске квадрокоптера в воздух модель "веревки" перестала рваться (видео [по ссылке](https://drive.google.com/file/d/1_CACtI46rNcJEWcClfJIrtCXglPT_Koy/view?usp=sharing) ).

**Comment by NatashaPinegina** [comment]
Замечания по отчету в Wiki исправлены.
