### ISSUE TITLE
Заполнить страничку "Участники проекта"

### ISSUE THREAD

**Issue by sergmin** [DRONE520/DRONE520-main#7]
Заполнить страничку "[Участники проекта"](https://github.com/DRONE520/DRONE520-main/wiki/%D0%A3%D1%87%D0%B0%D1%81%D1%82%D0%BD%D0%B8%D0%BA%D0%B8-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0) в формате: ФИО: ник

**Comment by diana-vahomskaya** [comment]
Сделано

**Comment by sergmin** [comment]
https://github.com/albina666 отсутствует в списке участников проекта

**Comment by sergmin** [comment]
Так что с albina666? Почему ее нет в списке участников проекта.

**Comment by diana-vahomskaya** [comment]
Я не знаю, я ей приглашение в проект давно скинула, она все висит в списке приглашенных

**Comment by sergmin** [comment]
> Я не знаю, я ей приглашение в проект давно скинула, она все висит в списке приглашенных

Позвоните, напишите ей смс.
